services:
  db:
    image: postgres:18
    container_name: pekko-game-db
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepass
      POSTGRES_DB: gamedb
    ports:
      - "5432:5432"
    volumes:
      - pekko-game-db-data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: pekko-game-redis
    ports:
      - "6379:6379"

volumes:
  pekko-game-db-data:
