package com.andy327.persistence.db

import java.time.Instant
import java.util.UUID

import cats.effect.IO

/** A registered account — the server-owned identity behind an issued JWT.
  *
  * The `id` is generated by this layer and becomes the subject the token attests to; it is never supplied by the
  * client. `passwordHash` is an opaque PHC string (the `argon2id` hash encoding) and is `None` for accounts that
  * authenticate without a local password (e.g. a future federated/OAuth identity), keeping the schema additive.
  *
  * @param id server-assigned unique identifier; the authenticated player's id
  * @param username display name surfaced to other players
  * @param email login identifier; unique case-insensitively across accounts
  * @param passwordHash opaque password hash, or `None` for passwordless accounts
  * @param createdAt server timestamp when the account was created
  */
final case class Account(
    id: UUID,
    username: String,
    email: String,
    passwordHash: Option[String],
    createdAt: Instant
)

object UserRepository {

  /** Reasons [[UserRepository.create]] can reject a registration. */
  sealed trait CreateError
  object CreateError {

    /** An account with the same email (case-insensitively) already exists. */
    case object EmailAlreadyExists extends CreateError
  }
}

/** Repository for registered accounts, the store of record for authenticatable identities.
  *
  * This is the backbone of real authentication: identity stops being a value the client asserts and becomes a row the
  * server owns. Credential verification and token issuance read from here; the repository itself is
  * credential-mechanism agnostic — it stores an opaque password hash and is structured so federated identities can be
  * layered on without schema churn.
  */
trait UserRepository {

  /** Runs any needed initialization, such as creating the accounts table. */
  def initialize(): IO[Unit]

  /** Look up an account by its id. `None` if no such account exists. */
  def findById(id: UUID): IO[Option[Account]]

  /** Look up an account by email, matched case-insensitively. `None` if no such account exists. */
  def findByEmail(email: String): IO[Option[Account]]

  /** Create a new account, generating its id and creation timestamp.
    *
    * Returns `Left(EmailAlreadyExists)` if the email is already taken (enforced atomically, not via a prior read), and
    * `Right(account)` with the persisted row otherwise.
    */
  def create(
      username: String,
      email: String,
      passwordHash: Option[String]
  ): IO[Either[UserRepository.CreateError, Account]]

  /** Replace the stored password hash for an account (e.g. rehashing on login when parameters are raised, or a future
    * password change). A no-op if the account does not exist.
    */
  def updatePasswordHash(id: UUID, passwordHash: String): IO[Unit]
}
