name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests and Coverage report
    runs-on: ubuntu-latest

    env:
      TESTCONTAINERS_RYUK_DISABLED: true
      DOCKER_HOST: unix:///var/run/docker.sock

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up SBT
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Cache SBT and Ivy2
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-cache-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            sbt-cache-${{ runner.os }}-

      - name: Run tests
        run: sbt clean coverage test

      - name: Coverage Report
        run: sbt coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true

  formatting:
    name: Scalafmt and Scalafix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
      - run: sbt scalafmtSbtCheck scalafmtCheckAll
      - run: sbt "scalafixAll --check"
